let foodItem = [
    { id: 1, foodName: "pongal vadai", category: "breakfast", type: "Veg", rating: 4.7, price: 100, img: "images/pongal.jpg", brand: "Anandhaas", cuisine: "IC" },
    { id: 2, foodName: "poori (2 pair)", category: "breakfast", type: "Veg", rating: 4.6, price: 60, img: "images/poori.jpg", brand: "Anandhaas", cuisine: "IC" },
    { id: 3, foodName: "Idly (2 pair)", category: "breakfast", type: "Veg", rating: 4.6, price: 40, img: "images/idly.jpg", brand: "Annapoorna", cuisine: "IC" },
    { id: 4, foodName: "Dosa (2 pair)", category: "breakfast", type: "Veg", rating: 4.6, price: 80, img: "images/dosa.jpeg", brand: "Annapoorna", cuisine: "IC" },
    { id: 5, foodName: "paneer tikka", category: "paneer", type: "Veg", rating: 4.8, price: 180, img: "images/paneer tikka.jpeg", brand: "Anandhaas", cuisine: "IC" },
    { id: 6, foodName: "kadai paneer", category: "paneer", type: "Veg", rating: 4.4, price: 120, img: "images/kadai paneer.jpg", brand: "Anandhaas", cuisine: "IC" },
    { id: 7, foodName: "palak paneer", category: "paneer", type: "Veg", rating: 4.5, price: 140, img: "images/palak paneer.jpeg", brand: "Anandhaas", cuisine: "IC" },
    { id: 8, foodName: "chicken tikka masala", category: "chicken", type: "N/Veg", rating: 4.6, price: 130, img: "images/chicken tikka masala.jpg", brand: "Mc Delivery", cuisine: "IC" },
    { id: 9, foodName: "Butter chicken", category: "chicken", type: "N/Veg", rating: 4.6, price: 150, img: "images/butter chicken.jpg", brand: "Mc Delivery", cuisine: "IC" },
    { id: 10, foodName: "tandoori", category: "BBQ", type: "N/Veg", rating: 4.8, price: 250, img: "images/tandoori.jpg", brand: "KFC", cuisine: "IC" },
    { id: 11, foodName: "grill (half)", category: "BBQ", type: "N/Veg", rating: 4.9, price: 290, img: "images/grill half.jpg", brand: "KFC", cuisine: "IC" },
    { id: 12, foodName: "grill (full)", category: "BBQ", type: "N/Veg", rating: 4.9, price: 550, img: "images/grill full.jpg", brand: "KFC", cuisine: "IC" },
    { id: 13, foodName: "Non veg meals", category: "meals", type: "N/Veg", rating: 4.9, price: 180, img: "images/nonveg meals.jpg", brand: "dindigul thalapakatti", cuisine: "IC" },
    { id: 14, foodName: "veg meals", category: "meals", type: "Veg", rating: 4.9, price: 160, img: "images/veg meals.jpg", brand: "Annapoorna", cuisine: "IC" },
    { id: 15, foodName: "bucket biryani (1/2kg)", category: "bucket biryani", type: "N/Veg", rating: 4.5, price: 180, img: "images/bucket briyani dt.jpeg", brand: "dindigul thalapakatti", cuisine: "IC" },
    { id: 16, foodName: "bucket biryani (1kg)", category: "bucket biryani", type: "N/Veg", rating: 4.5, price: 280, img: "images/bucket briyani dt.jpeg", brand: "dindigul thalapakatti", cuisine: "IC" },
    { id: 17, foodName: "bucket biryani (1/2kg)", category: "bucket biryani", type: "N/Veg", rating: 4.6, price: 200, img: "images/bucket briyani mc.jpeg", brand: "Mc Delivery", cuisine: "IC" },
    { id: 18, foodName: "bucket biryani (1kg)", category: "bucket biryani", type: "N/Veg", rating: 4.6, price: 300, img: "images/bucket briyani mc.jpeg", brand: "Mc Delivery", cuisine: "IC" },
    { id: 19, foodName: "Chicken biryani", category: "biryani", type: "N/Veg", rating: 4.4, price: 180, img: "images/chicken briyani.jpeg", brand: "dindigul thalapakatti", cuisine: "IC" },
    { id: 20, foodName: "Mutton Biryani", category: "biryani", type: "N/Veg", rating: 4.8, price: 350, img: "images/mutton briyani.jpeg", brand: "dindigul thalapakatti", cuisine: "IC" },
    { id: 21, foodName: "Egg Biryani", category: "biryani", type: "N/Veg", rating: 4.3, price: 100, img: "images/egg briyani.jpeg", brand: "dindigul thalapakatti", cuisine: "IC" },
    { id: 22, foodName: "Fish Biryani", category: "biryani", type: "N/Veg", rating: 4.5, price: 200, img: "images/fish briyani.jpg", brand: "dindigul thalapakatti", cuisine: "IC" },
    { id: 23, foodName: "Chicken 65 Biryani", category: "biryani", type: "N/Veg", rating: 4.6, price: 220, img: "images/chicken 65 briyani.jpeg", brand: "dindigul thalapakatti", cuisine: "IC" },
    { id: 24, foodName: "Hyderabad Biryani", category: "biryani", type: "N/Veg", rating: 4.8, price: 250, img: "images/hyderabad briyani.jpeg", brand: "dindigul thalapakatti", cuisine: "IC" },
    { id: 25, foodName: "Mushroom Biryani", category: "biryani", type: "Veg", rating: 4.7, price: 160, img: "images/mushroom briyani.jpeg", brand: "Anandhaas", cuisine: "IC" },
    { id: 26, foodName: "Vegetable Biryani", category: "biryani", type: "Veg", rating: 4.6, price: 140, img: "images/vegetable briyani.jpeg", brand: "Annapoorna", cuisine: "IC" },
    { id: 27, foodName: "Omelet", category: "cheese", type: "Veg", rating: 4.6, price: 350, img: "images/omelet.jpg", brand: "Annapoorna", cuisine: "FC" },
    { id: 28, foodName: "Nicoise salad", category: "cheese", type: "Veg", rating: 4.5, price: 250, img: "images/nicoise salad.jpeg", brand: "Anandhaas", cuisine: "FC" },
    { id: 29, foodName: "Beef bourguignon", category: "fry", type: "N/Veg", rating: 4.3, price: 320, img: "images/beef bourguignon.jpg", brand: "Mc Delivery", cuisine: "FC" },
    { id: 30, foodName: "Cassoulet", category: "cheese", type: "Veg", rating: 4.8, price: 200, img: "images/cassoulet.jpg", brand: "Anandhaas", cuisine: "FC" },
    { id: 31, foodName: "Veal stew", category: "chicken", type: "N/Veg", rating: 4.5, price: 180, img: "images/veal stew.jpeg", brand: "Mc Delivery", cuisine: "FC" },
    { id: 32, foodName: "Raclette", category: "cheese", type: "Veg", rating: 4.4, price: 280, img: "images/raclette.jpeg", brand: "Annapoorna", cuisine: "FC" },
    { id: 33, foodName: "Tartiflette", category: "chicken", type: "N/Veg", rating: 4.1, price: 190, img: "images/tartiflette.jpeg", brand: "Mc Delivery", cuisine: "FC" },
    { id: 34, foodName: "Croque monsieur", category: "fry", type: "N/Veg", rating: 4.2, price: 270, img: "images/croque monsieur.jpg", brand: "KFC", cuisine: "FC" },
    { id: 35, foodName: "Thai stir fry", category: "fry", type: "N/Veg", rating: 4.1, price: 290, img: "images/thai stir fry.jpeg", brand: "Mc Delivery", cuisine: "TC" },
    { id: 36, foodName: "Green chilli panner", category: "paneer", type: "Veg", rating: 4.8, price: 250, img: "images/green chilli paneer.jpeg", brand: "Annapoorna", cuisine: "TC" },
    { id: 37, foodName: "Thai green curry", category: "paneer", type: "Veg", rating: 4.6, price: 240, img: "images/thai green curry.jpeg", brand: "Annapoorna", cuisine: "TC" },
    { id: 38, foodName: "Coconut noodel", category: "fry", type: "Veg", rating: 4.8, price: 220, img: "images/coconut noodel.jpeg", brand: "Pizza Hut", cuisine: "TC" },
    { id: 39, foodName: "Thai fried rice", category: "fry", type: "Veg", rating: 3.9, price: 180, img: "images/thai fried rice.jpeg", brand: "Mc Delivery", cuisine: "TC" },
    { id: 40, foodName: "Thai meals", category: "meals", type: "Veg", rating: 4.2, price: 160, img: "images/thai meals.jpeg", brand: "Annapoorna", cuisine: "TC" },
    { id: 41, foodName: "Thai's laab", category: "fry", type: "N/Veg", rating: 4.5, price: 290, img: "images/thai laab.jpeg", brand: "KFC", cuisine: "TC" },
    { id: 42, foodName: "Fried corn", category: "fry", type: "Veg", rating: 4.4, price: 200, img: "images/fried corn.jpeg", brand: "Pizza Hut", cuisine: "MC" },
    { id: 43, foodName: "Ranch eggs", category: "fry", type: "Veg", rating: 4.6, price: 250, img: "images/ranch eggs.jpeg", brand: "Pizza Hut", cuisine: "MC" },
    { id: 44, foodName: "Plow disc (BBQ)", category: "BBQ", type: "Veg", rating: 4.3, price: 300, img: "images/plow disc.jpg", brand: "Anandhaas", cuisine: "MC" },
    { id: 45, foodName: "Tacos", category: "chicken", type: "N/Veg", rating: 4.4, price: 220, img: "images/tacos.jpg", brand: "KFC", cuisine: "MC" },
    { id: 46, foodName: "Burritos", category: "BBQ", type: "N/Veg", rating: 4.2, price: 250, img: "images/burrito.jpeg", brand: "KFC", cuisine: "MC" },
    { id: 47, foodName: "Pibil pork stew", category: "fry", type: "N/Veg", rating: 4.5, price: 290, img: "images/pibil pork stew.jpg", brand: "KFC", cuisine: "MC" },
    { id: 48, foodName: "Nogada pepper", category: "cheese", type: "Veg", rating: 4.1, price: 210, img: "images/nogada pepper.jpeg", brand: "KFC", cuisine: "MC" },
    { id: 49, foodName: "Quesadilla", category: "pizza", type: "Veg", rating: 4.7, price: 240, img: "images/quesadilla.jpg", brand: "Pizza Hut", cuisine: "MC" },
    { id: 50, foodName: "Tortilla pizza", category: "pizza", type: "N/Veg", rating: 4.5, price: 250, img: "images/tortilla pizza.jpg", brand: "Pizza Hut", cuisine: "MC" },
    { id: 51, foodName: "Caprese pizza", category: "pizza", type: "N/Veg", rating: 4.7, price: 280, img: "images/caprese pizza.jpeg", brand: "Pizza Hut", cuisine: "MC" },
    { id: 52, foodName: "Margherita pizza", category: "pizza", type: "N/Veg", rating: 4.8, price: 300, img: "images/margherita pizza.jpeg", brand: "Pizza Hut", cuisine: "MC" },
    { id: 53, foodName: "Sicilian pizza", category: "pizza", type: "Veg", rating: 4.4, price: 250, img: "images/sicilian pizza.jpg", brand: "Pizza Hut", cuisine: "MC" },
]

export {foodItem};